- name: Install OpenJDK 17
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes

- name: Install Tomcat 9
  apt:
    name: tomcat9
    state: present
    update_cache: yes

- name: Ensure Tomcat is running
  service:
    name: tomcat9
    state: started
    enabled: yes
